---

helga_system_packages:
  - python-devel
  - git
  - python-virtualenv
  - mongodb-server
  - gcc-c++

helga_ssl_requirements:
  - openssl
  - openssl-devel
  #- libcurl4-openssl-dev
  #- libffi-dev

circus_system_packages:
  - libzmq-dev
  - libevent-dev
