---

- hosts: local

  connection: local

  vars:
    version: 0-dev # a stub, should be passed in the CLI like '--extra-vars "version=1.23.45" '


  tasks:
     - name: check if ceph repo exists
       stat: path='./ceph'
       register: 'ceph_repo'

     - name: clone the ceph repository
       git: repo=git@jenkins.front.sepia.ceph.com:ceph/ceph dest=ceph
       when: ceph_repo.stat.exists is defined and ceph_repo.stat.exists == false
           #is defined and not ceph_repo.stat.isdir

     - name: rename origin to jenkins
       command: git remote rename origin jenkins chdir=ceph
       ignore_errors: yes

     - name: spit out the remote names
       command: git remote -v chdir=ceph

       # FIXME: branch depends on type of build
     - name: git checkout next branch
       command: git checkout next chdir=ceph

     - name: git submodule update
       command: git submodule update --init chdir=ceph

       # FIXME: version depends on type of build
     - name: set the debian version
       command: dch -v 0.74-1 chdir=ceph

       # FIXME: version depends on type of build
     - name: commit the version changes
       command: git commit -a -m "v0.74" chdir=ceph

       # FIXME: again need the version comming from the build
       # from script: /srv/ceph-build/tag_release.sh
       # Contents of tag_release.sh
     - name: tag and commit the version
       command: git tag -s "v0.74" -u 17ED316D -m "v0.74" chdir=ceph

     - name: push changes to jenkins git repo
       command: git push jenkins next chdir=ceph

       # FIXME: again need the version comming from the build
     - name: push the newly created tag
       command: git push jenkins v0.74 chdir=ceph

     #- name: set the GNUPGHOME env variable
     #  environment:
     #    GNUPGHOME: ~/build/gnupg.ceph-release/

     - name: ensure GPG keys exist for release
       command: gpg --list-keys
       register: command_result
       failed_when: "'17ED316D' not in command_result.stdout"
       environment:
         GNUPGHOME: ~/build/gnupg.ceph-release/

# TODO
#- hosts: slaves
#  user: jenkins
#  sudo: True
