---

- hosts: production
  roles:
    - common
  vars:
     ansible_ssh_user: "ubuntu"

     # bot specific vars
     venv: "{{ helga_home }}/venv"
     helga_nick: 'kraken'
     helga_irc_host: irc.devel.redhat.com
     helga_irc_port: 6667
     helga_use_ssl: false

     helga_irc_channels:
       - rh-ceph
       - ceph
       - octo
       - rh-ceph-qe

     helga_operators: ['alfredodeza']
     helga_default_plugins:
       - dubstep
       - facts
       - help
       - manager
       - meant_to_say
       - oneliner
       - operator
       - poems
       - reminders
       - stfu
       # custom ones
       - norris
       - redmine
       - yall
       - ugrep
       - karma
       - wut
       - karma

     helga_external_plugins:
       - git+https://github.com/alfredodeza/helga-norris#egg=helga-norris
       - git+https://github.com/alfredodeza/helga-redmine#egg=helga-redmine
       - git+https://github.com/alfredodeza/helga-yall#egg=helga-yall
       - git+https://github.com/alfredodeza/helga-ugrep#egg=helga-ugrep
       - git+https://github.com/alfredodeza/helga-excuses#egg=helga-excuses
       - git+https://github.com/coddingtonbear/helga-karma#egg=helga-karma
       - git+https://github.com/alfredodeza/helga-wut#egg=helga-wut
