---

- hosts: os1
  roles:
    - common
  vars:
     ansible_ssh_user: "centos"

     # bot specific vars
     venv: "{{ helga_home }}/venv"
     helga_nick: 'kraken'
     helga_irc_host: irc.devel.redhat.com
     helga_irc_port: 6667
     helga_use_ssl: false
     helga_cmd_prefix: '!'

     helga_irc_channels:
       - rh-ceph
       - ceph
       - octo
       - rh-ceph-qe
       - chatops
       - seg-team

     helga_operators: ['alfredodeza', 'ktdreyer', 'andrewschoen']
     helga_default_plugins:
       - dubstep
       - help
       - manager
       - meant_to_say
       - oneliner
       - operator
       - stfu
       # custom ones
       - norris
       - redmine
       - yall
       - ugrep
       - wut
       - jenkins
       - excuses
       - poems
       - reminders
       - karma

     helga_external_plugins:
       - git+https://github.com/alfredodeza/helga-norris#egg=helga-norris
       - git+https://github.com/alfredodeza/helga-yall#egg=helga-yall
       - git+https://github.com/alfredodeza/helga-ugrep#egg=helga-ugrep
       - git+https://github.com/alfredodeza/helga-wut#egg=helga-wut
       - git+https://github.com/coddingtonbear/helga-karma#egg=helga-karma
       - git+https://github.com/alfredodeza/helga-jenkins#egg=helga-jenkins
       - git+https://github.com/alfredodeza/helga-excuses#egg=helga-excuses

     helga_pypi_plugins:
       - helga-redmine
       - helga-poems
       - helga-reminders
